- name: 源码安装Java1.8.0_112
  hosts: all
  tasks:
    - name: 创建目录
      file:
        path: /data/software
        state: directory
    - name: 下载源码包
      unarchive: 
        src: http://mirrors.linuxeye.com/jdk/jdk-8u112-linux-x64.tar.gz
        dest: /data/software/
        remote_src: True
    
    - name: 添加环境变量
      blockinfile:
        dest: /etc/profile
        marker: '#JAVA_HOME_ENV_{mark}'
        block: |
          export JAVA_HOME=/data/software/jdk1.8.0_112
          export PATH=$JAVA_HOME/bin:\$PATH
          export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
      notify:
      - source env
    
  handlers:
    - name: source env
      shell: source /etc/profile
