- name: 安装游戏服
  hosts: all
  #vars:
  #  pkg: "http://download.nust.na/pub2/apache/zookeeper/zookeeper-3.4.9/zookeeper-3.4.9.tar.gz"
  #  dir: /data/project/game-service
  tasks:
    - name: 创建目录
      file:
        path: "{{ dir }}"
        state: directory

    - name: 下载tar包
      unarchive:
        src: "{{ pkg }}"
        dest: "{{ dir }}"
        remite_src: True
