- name: 安装游戏服
  hosts: all
  #vars:
  #  pkg: "https://#"
  #  dir: /data/
  tasks:
    - name: 创建目录
      file:
        path: "{{ dir }}"
        state: directory

    - name: 下载tar包
      unarchive:
        src: "{{ pkg }}"
        dest: "{{ dir }}"
        remite_src: True
